# Generated by Django 4.2.2 on 2023-06-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
